# Generated by Django 2.2 on 2019-04-12 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='资产组名称', max_length=32, unique=True, verbose_name='资产组名称')),
                ('remark', models.CharField(help_text='备注', max_length=32, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'resources_assetgroup',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='主机名', max_length=64, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(help_text='IP地址', unique=True, verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, help_text='端口', verbose_name='端口')),
                ('username', models.CharField(help_text='远程登陆账号', max_length=32, verbose_name='远程登陆账号')),
                ('password', models.CharField(help_text='远程登陆密码', max_length=32, verbose_name='远程登陆密码')),
                ('is_active', models.BooleanField(help_text='激活', verbose_name='激活')),
                ('remark', models.CharField(help_text='备注', max_length=32, null=True, verbose_name='备注')),
                ('group', models.ForeignKey(help_text='资产组', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.AssetGroup', verbose_name='资产组')),
            ],
            options={
                'db_table': 'resources_asset',
                'ordering': ['id'],
            },
        ),
    ]
