# Generated by Django 2.2 on 2019-04-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色名称', max_length=32, unique=True, verbose_name='角色名称')),
                ('is_active', models.BooleanField(help_text='激活', verbose_name='激活')),
                ('remark', models.CharField(help_text='备注', max_length=32, null=True, verbose_name='备注')),
                ('asset', models.ManyToManyField(help_text='授权资产', to='assets.Asset', verbose_name='授权资产')),
            ],
            options={
                'db_table': 'resources_perm',
                'ordering': ['id'],
            },
        ),
    ]
