# Generated by Django 2.2 on 2019-04-12 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perm',
            name='user',
            field=models.ManyToManyField(help_text='授权用户', to=settings.AUTH_USER_MODEL, verbose_name='授权用户'),
        ),
    ]
